---
title: "Metabarcoding pipeline script writer"
output: html_notebook
---

# Enter run info
```{r}
# Enter your run info here
miniseqDir='/path/to/miniseq-dir'
samplesheet='/path/to/samplesheet'
email='youremail@duke.edu'
scripts.dir='/path/to/where-scripts-are-stored'

## For example
# miniseqDir='/hpc/group/ldavidlab/users/tjk30/SAGE-trnL-20230707/230705_MN00462_0054_A000H5JGF5'
# samplesheet='/hpc/group/ldavidlab/users/tjk30/SAGE-trnL-20230707/samplesheet.csv'
# email='teresa.kaza@duke.edu'
# scripts.dir='/hpc/group/ldavidlab/users/tjk30/mb-pipeline/pipeline'

```

# Demultiplex
Usage:
/path/to/demux-barcode.sh /miniseq-dir /path/to/samplesheetname /path/to/metabarcoding.sif
```{r}
qiime.container='/hpc/group/ldavidlab/qiime2.sif'
demux.container='/hpc/group/ldavidlab/metabarcoding.sif'

print('Copy this command:')
print(paste0(
  'sbatch --mail-user=',email,' ',scripts.dir,'/demux-barcodes.sh ', miniseqDir, ' ', samplesheet, ' ', demux.container
  ))
```
Paste the above command. Ie:
```{bash}
# Example
# sbatch --mail-user=youremail@duke.edu /path/to/demux-barcodes.sh /path/to/miniseq-dir /path/to/samplesheet /hpc/group/ldavidlab/metabarcoding.sif
```
# Amplicon specific pipeline
## Enter demultiplexed reads path
```{r}
# Enter the path to your demultiplexed reads here
demux.dir='/path/to/demultiplexed'
# For example
# demux.dir=file.path(dirname(miniseqDir),
#                     paste0(format(Sys.Date(),'%Y%m%d'),'_results'),
#                     'demultiplexed')
# print(demux.dir)



```

## trnL pipeline
```{r}
print('Copy this:')
print(paste0(
  'sbatch --mail-user=',email,' ',scripts.dir,'/trnL-pipeline.sh ', demux.dir, ' ', qiime.container
))
```



## 12SV5 pipeline
```{r}
print('Copy this:')
print(paste0(
  'sbatch --mail-user=',email,' ',scripts.dir,'/12SV5-pipeline.sh ', demux.dir, ' ', qiime.container
))
```
## Count reads
```{r}
print('trnL')
print(paste0('sbatch --mail-user=',email,' ',scripts.dir,'/count-reads.sh ',dirname(demux.dir),'/',format(Sys.Date(),'%Y%m%d'),'_trnL_output', ' ', scripts.dir, ' ',qiime.container
))
print('12SV5')
print(paste0('sbatch --mail-user=',email,' ',scripts.dir,'/count-reads.sh ',dirname(demux.dir),'/',format(Sys.Date(),'%Y%m%d'),'_12SV5_output', ' ',scripts.dir, ' ', qiime.container
))
```

